#!/usr/bin/env bash
# Concatenates the ES module source files in prototype/js/ into a single
# classic (non-module) script, prototype/js/bundle.js, so the page works
# when opened directly via file:// (browsers block `<script type="module">`
# under file://, but plain scripts are unaffected). Source files keep their
# export/import syntax untouched — Node still tests them as ES modules;
# this script only strips those two patterns in the generated copy.
set -euo pipefail

cd "$(dirname "$0")/../prototype"

{
  echo "// Generated by scripts/build-bundle.sh from js/kinetic-text.js, js/magnetic.js,"
  echo "// js/honeypot.js, js/main.js — do not edit by hand. Re-run the script after"
  echo "// changing any of those files."
  echo
  for file in js/kinetic-text.js js/magnetic.js js/honeypot.js js/main.js; do
    grep -v -E "^import .* from '.*';\$" "$file" | sed -E 's/^export //'
    echo
  done
} > js/bundle.js

echo "wrote prototype/js/bundle.js"
